name: CI for VoteApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('vote/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd vote
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run unit tests
    #   run: |
    #     # Add your command to run tests here
    #     cd vote
    #     pytest

    - name: Build Docker image
      run: docker build -t voteapp:${{ github.sha }} vote/.
    
    - name: Install Trivy
      run: |
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.53.0_Linux-64bit.deb

    - name: Scan Docker image with Trivy
      run: trivy image voteapp:${{ github.sha }} -f json -o trivy-report.json
  
    - name: Upload Trivy Report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.json

    - name: Log in to DockerHub
      if: success()
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag Docker image
      run: docker tag voteapp:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/voteapp:${{ github.sha }}
  
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/voteapp:${{ github.sha }}

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --failOnCVSS 7
          --enableRetired
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
         name: Depcheck report
         path: ${{github.workspace}}/reports

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      with:
        projectBaseDir: vote
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SAST Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        tools: "sast"
        failBuild: true

    - name: DAST Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'http://your_live_app_url_here'
        rulesFile: '.zap/rules.tsv'
        cmdOptions: '-J report.json'